/* generated by tools/atlas.py */
#ifndef PREY_ATLAS_H
#define PREY_ATLAS_H
#define ATLAS_W 256
#define ATLAS_H 256
#define ATLAS_BYTES 66624
#define SPR_ELEM_PHYS 0
#define SPR_ELEM_GUN 1
#define SPR_ELEM_FIRE 2
#define SPR_ELEM_ICE 3
#define SPR_ELEM_ELEC 4
#define SPR_ELEM_FORCE 5
#define SPR_ELEM_EARTH 6
#define SPR_ELEM_EXPEL 7
#define SPR_ELEM_DEATH 8
#define SPR_RES_WEAK 9
#define SPR_RES_RESIST 10
#define SPR_RES_NULL 11
#define SPR_RES_REFLECT 12
#define SPR_RES_DRAIN 13
#define SPR_RES_NORMAL 14
#define SPR_RES_UNKNOWN 15
#define SPR_RET_WEAK 16
#define SPR_RET_RESIST 17
#define SPR_RET_NULL 18
#define SPR_RET_REFLECT 19
#define SPR_RET_DRAIN 20
#define SPR_RET_NORMAL 21
#define SPR_RET_UNKNOWN 22
#define SPR_AIL_CHARM 23
#define SPR_AIL_POISON 24
#define SPR_AIL_MUTE 25
#define SPR_AIL_PANIC 26
#define SPR_AIL_SLEEP 27
#define SPR_BUFF_ATT_UP1 28
#define SPR_BUFF_ATT_UP2 29
#define SPR_BUFF_ATT_UP3 30
#define SPR_BUFF_ATT_UP4 31
#define SPR_BUFF_ATT_DN1 32
#define SPR_BUFF_ATT_DN2 33
#define SPR_BUFF_ATT_DN3 34
#define SPR_BUFF_ATT_DN4 35
#define SPR_BUFF_MAG_UP1 36
#define SPR_BUFF_MAG_UP2 37
#define SPR_BUFF_MAG_UP3 38
#define SPR_BUFF_MAG_UP4 39
#define SPR_BUFF_MAG_DN1 40
#define SPR_BUFF_MAG_DN2 41
#define SPR_BUFF_MAG_DN3 42
#define SPR_BUFF_MAG_DN4 43
#define SPR_BUFF_DEF_UP1 44
#define SPR_BUFF_DEF_UP2 45
#define SPR_BUFF_DEF_UP3 46
#define SPR_BUFF_DEF_UP4 47
#define SPR_BUFF_DEF_DN1 48
#define SPR_BUFF_DEF_DN2 49
#define SPR_BUFF_DEF_DN3 50
#define SPR_BUFF_DEF_DN4 51
#define SPR_BUFF_ACC_UP1 52
#define SPR_BUFF_ACC_UP2 53
#define SPR_BUFF_ACC_UP3 54
#define SPR_BUFF_ACC_UP4 55
#define SPR_BUFF_ACC_DN1 56
#define SPR_BUFF_ACC_DN2 57
#define SPR_BUFF_ACC_DN3 58
#define SPR_BUFF_ACC_DN4 59
#define SPR_WHITE 60
#define SPR_COUNT 61
static const unsigned char atlas_rects[SPR_COUNT][4] = {
    {231, 0, 24, 24}, /* ELEM_PHYS */
    {0, 33, 24, 24}, /* ELEM_GUN */
    {25, 33, 24, 24}, /* ELEM_FIRE */
    {50, 33, 24, 24}, /* ELEM_ICE */
    {75, 33, 24, 24}, /* ELEM_ELEC */
    {100, 33, 24, 24}, /* ELEM_FORCE */
    {125, 33, 24, 24}, /* ELEM_EARTH */
    {150, 33, 24, 24}, /* ELEM_EXPEL */
    {175, 33, 24, 24}, /* ELEM_DEATH */
    {200, 33, 20, 20}, /* RES_WEAK */
    {221, 33, 20, 20}, /* RES_RESIST */
    {0, 58, 20, 20}, /* RES_NULL */
    {21, 58, 20, 20}, /* RES_REFLECT */
    {42, 58, 20, 20}, /* RES_DRAIN */
    {63, 58, 20, 20}, /* RES_NORMAL */
    {84, 58, 20, 20}, /* RES_UNKNOWN */
    {0, 0, 32, 32}, /* RET_WEAK */
    {33, 0, 32, 32}, /* RET_RESIST */
    {66, 0, 32, 32}, /* RET_NULL */
    {99, 0, 32, 32}, /* RET_REFLECT */
    {132, 0, 32, 32}, /* RET_DRAIN */
    {165, 0, 32, 32}, /* RET_NORMAL */
    {198, 0, 32, 32}, /* RET_UNKNOWN */
    {21, 121, 16, 16}, /* AIL_CHARM */
    {38, 121, 16, 16}, /* AIL_POISON */
    {55, 121, 16, 16}, /* AIL_MUTE */
    {72, 121, 16, 16}, /* AIL_PANIC */
    {89, 121, 16, 16}, /* AIL_SLEEP */
    {105, 58, 20, 20}, /* BUFF_ATT_UP1 */
    {126, 58, 20, 20}, /* BUFF_ATT_UP2 */
    {147, 58, 20, 20}, /* BUFF_ATT_UP3 */
    {168, 58, 20, 20}, /* BUFF_ATT_UP4 */
    {189, 58, 20, 20}, /* BUFF_ATT_DN1 */
    {210, 58, 20, 20}, /* BUFF_ATT_DN2 */
    {231, 58, 20, 20}, /* BUFF_ATT_DN3 */
    {0, 79, 20, 20}, /* BUFF_ATT_DN4 */
    {21, 79, 20, 20}, /* BUFF_MAG_UP1 */
    {42, 79, 20, 20}, /* BUFF_MAG_UP2 */
    {63, 79, 20, 20}, /* BUFF_MAG_UP3 */
    {84, 79, 20, 20}, /* BUFF_MAG_UP4 */
    {105, 79, 20, 20}, /* BUFF_MAG_DN1 */
    {126, 79, 20, 20}, /* BUFF_MAG_DN2 */
    {147, 79, 20, 20}, /* BUFF_MAG_DN3 */
    {168, 79, 20, 20}, /* BUFF_MAG_DN4 */
    {189, 79, 20, 20}, /* BUFF_DEF_UP1 */
    {210, 79, 20, 20}, /* BUFF_DEF_UP2 */
    {231, 79, 20, 20}, /* BUFF_DEF_UP3 */
    {0, 100, 20, 20}, /* BUFF_DEF_UP4 */
    {21, 100, 20, 20}, /* BUFF_DEF_DN1 */
    {42, 100, 20, 20}, /* BUFF_DEF_DN2 */
    {63, 100, 20, 20}, /* BUFF_DEF_DN3 */
    {84, 100, 20, 20}, /* BUFF_DEF_DN4 */
    {105, 100, 20, 20}, /* BUFF_ACC_UP1 */
    {126, 100, 20, 20}, /* BUFF_ACC_UP2 */
    {147, 100, 20, 20}, /* BUFF_ACC_UP3 */
    {168, 100, 20, 20}, /* BUFF_ACC_UP4 */
    {189, 100, 20, 20}, /* BUFF_ACC_DN1 */
    {210, 100, 20, 20}, /* BUFF_ACC_DN2 */
    {231, 100, 20, 20}, /* BUFF_ACC_DN3 */
    {0, 121, 20, 20}, /* BUFF_ACC_DN4 */
    {106, 121, 8, 8}, /* WHITE */
};
#endif
